%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/rolling/.*$
%global __requires_exclude_from ^/opt/ros/rolling/.*$

Name:           ros-rolling-tracetools-trace
Version:        6.3.0
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS tracetools_trace package

License:        Apache 2.0
URL:            https://index.ros.org/p/tracetools_trace/
Source0:        %{name}-%{version}.tar.gz

Requires:       %{name}-runtime%{?_isa?} = %{version}-%{release}
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}

%description
Tools for setting up tracing sessions.

%package runtime
Summary:        Runtime-only files for tracetools_trace package
Requires:       lttng-tools
Requires:       python3-lttng
Requires:       ros-rolling-ros-workspace-runtime
BuildRequires:  python%{python3_pkgversion}-devel
BuildRequires:  ros-rolling-ros-workspace-devel

%if 0%{?with_tests}
BuildRequires:  python%{python3_pkgversion}-pytest
BuildRequires:  ros-rolling-ament-copyright-devel
BuildRequires:  ros-rolling-ament-flake8-devel
BuildRequires:  ros-rolling-ament-mypy-devel
BuildRequires:  ros-rolling-ament-pep257-devel
BuildRequires:  ros-rolling-ament-xmllint-devel
%endif

%description runtime
Runtime-only files for tracetools_trace package

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%py3_install -- --prefix "/opt/ros/rolling"

for f in \
    /opt/ros/rolling/include/ \
    /opt/ros/rolling/share/ament_index/resource_index/packages/ \
    /opt/ros/rolling/share/tracetools_trace/cmake/ \
    /opt/ros/rolling/share/tracetools_trace/package.dsv \
    /opt/ros/rolling/share/tracetools_trace/package.xml \
; do
    if [ -e %{buildroot}$f ]; then echo $f; fi
done > devel_files

%if 0%{?with_tests}
%check
# Look for a directory with a name indicating that it contains tests
TEST_TARGET=$(ls -d * | grep -m1 "\(test\|tests\)" ||:)
if [ -n "$TEST_TARGET" ] && %__python3 -m pytest --version; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/rolling/setup.sh" ]; then . "/opt/ros/rolling/setup.sh"; fi
%__python3 -m pytest $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files -f devel_files

%files runtime
/opt/ros/rolling
%exclude /opt/ros/rolling/include/
%exclude /opt/ros/rolling/share/ament_index/resource_index/packages/
%exclude /opt/ros/rolling/share/tracetools_trace/cmake
%exclude /opt/ros/rolling/share/tracetools_trace/package.dsv
%exclude /opt/ros/rolling/share/tracetools_trace/package.xml

%changelog
* Tue Apr 18 2023 Christophe Bedard <bedard.christophe@gmail.com> - 6.3.0-1
- Autogenerated by Bloom

* Tue Apr 18 2023 Christophe Bedard <bedard.christophe@gmail.com> - 6.2.0-1
- Autogenerated by Bloom

* Thu Apr 13 2023 Christophe Bedard <bedard.christophe@gmail.com> - 6.1.0-1
- Autogenerated by Bloom

* Wed Apr 12 2023 Christophe Bedard <bedard.christophe@gmail.com> - 6.0.0-1
- Autogenerated by Bloom

* Tue Mar 21 2023 Christophe Bedard <bedard.christophe@gmail.com> - 5.1.0-2
- Autogenerated by Bloom

